### ISSUE TITLE
Commits from one dev are not pushed by another

### ISSUE THREAD

**Issue by danielbsig** [ingydotnet/git-subrepo#326] opened 2017-12-07 15:39 UTC
Hi,

I may be misunderstanding how things should work using subrepo. I have a "client repo", there are two developers working on that repo: myself and another developer.

The scenario is as follows:
1. Developer X pushes some changes to the parent repo, including changes to code which belong to the subrepo within the parentrepo.
2. Developer Y pulls said changes to his local repository.
3. Developer Y realizes that the lates changes have not been pushed to the subrepo, although they are present in the parent repo.
4. Developer Y issues the "git subrepo push <subrepo>" command, but receives the following message:

"Subrepo '<name of subrepo>' has no new commits to push."

Should developer Y not be able to push changes made by X? Or am I misunderstanding something?

**Comment by grimmySwe** [comment] 2017-12-08 09:30
@danielbsig No, you are not misunderstanding somehing. From you description you should not get the "Subrepo '' has no new commits to push."

Just to be sure, please double check the contents of the .gitrepo file. There you should see the current known state. And you can also perform the `git subrepo branch <subrepo` to create a local worktree and inspect whet subrepo sees as it's current state.

**Comment by bitdivision** [comment] 2017-12-13 12:10
We seem to be having this issue too, where sometimes we will see 'has no new commits to push' but there have been new commits that were merged into the parent repo affecting that subrepo.

I guess we will need to make a repo to reproduce this.

**Comment by grimmySwe** [comment] 2017-12-13 12:12
@bitdivision If you can reproduce it, it would be very valuable!

**Comment by bitdivision** [comment] 2017-12-13 14:08
I'm unable to reproduce it on a public repository. 

@grimmySwe Is there anything I can give you that would help to debug this? I can't share the repo we're having a problem with, but I'll include some information on what's happened here:

We have recently switched to subrepo and started committing everything to the parent repository. The general process is to commit to a branch and pull request into master. Subrepos are then pushed after the Pull request has been merged to make sure everything stays in sync.

We are all using git subrepo on branch `release/0.4.0`. Subrepos are all stored in a `modules` directory.

In this case, someone has just merged a pull request into the parent master which touches subrepo A and subrepo B. That person then attempted to push the subrepos (using `git subrepo push <subrepo>`), which worked correctly for subrepo A but gave the 'has no new commits to push' message on subrepo B. I am receiving the same message when attempting to push.

The subrepo B .gitrepo file looks as follows:
```[subrepo]
    remote = git@xxx.com:yyy/zzz.git
    branch = master
    commit = 639869c139118a1dbcbc5f69e9347afff1aefa9d
    parent = d2e5b4744dced7a588b1c76c4c832ab87fed1387
    method = merge
    cmdver = 0.4.0
```

Looking at subrepo B, the latest commit on master is: `639869c139118a1dbcbc5f69e9347afff1aefa9d`
The parent commit listed in the .gitrepo file is a fairly old merge commit.

Is there any other information I can give you to help work this out? I tried the `git subrepo branch <subrepo>` command, which said that the branch exists. Trying to checkout that branch says that it is already checked out in .git/. Looking at the branch in .git, the changes from the Pull Request are not there. And obviously I've triple checked that I do have the merge commit in my git log and that the code looks correct in the files.

Running `git subrepo push <subrepo B> -vd` gives:

```
>>> git rev-parse --verify HEAD
* Assert that working copy is clean: /home/bitdivision/xxx/yyy/zzz
* Check for worktree with branch subrepo/modules/<submodule_name>
  * Fetch the upstream: git@abc:<group_name>/<submodule_name>.git (master).
>>> git fetch --no-tags --quiet git@abc:<group_name>/<submodule_name>.git master
  * Get the upstream subrepo HEAD commit.
>>> git rev-parse FETCH_HEAD^0
  * Create ref 'refs/subrepo/modules/<submodule_name>/fetch'.
>>> git update-ref refs/subrepo/modules/<submodule_name>/fetch 639869c139118a1dbcbc5f69e9347afff1aefa9d
* Check upstream head against .gitrepo commit.
* Deleting old 'subrepo/modules/<submodule_name>' branch.
* Remove worktree: 
>>> git branch -D subrepo/modules/<submodule_name>
* Create subrepo branch 'subrepo/modules/<submodule_name>'.
  * Check if the 'subrepo/modules/<submodule_name>' branch already exists.
* Make sure that 'subrepo/modules/<submodule_name>' exists.
* Check if we have something to push
Subrepo 'modules/<submodule_name>' has no new commits to push.
```

**Comment by grimmySwe** [comment] 2017-12-13 15:07
@bitdivision You can run `git subrepo clean <subrepo>` first, then you should be able to `git subrepo branch <subrepo>`. 
That would give you a worktree with the current state as subrepo sees it.

**Comment by bitdivision** [comment] 2017-12-13 15:11
Ah, I see. I ran clean --all and then looked at the worktree, it contains the latest commits. I then attempted to push the subrepo and it works correctly.

So it seems that this was an issue with that branch being out of date?

**Comment by grimmySwe** [comment] 2017-12-13 15:13
Sounds like that. `subrepo pull` should do fetch automatically but `subrepo branch` doesn't. Please let me know if you find any other strange things or if you can reproduce it.

**Comment by grimmySwe** [comment] 2017-12-19 09:11
@danielbsig @bitdivision I close this issue now, but please don't hesitate to reopen it if you think it doesn't work!

**Closed by grimmySwe** 2017-12-19 09:11 UTC
