### ISSUE TITLE
Incorrect branch creation when there are merge commits for branches created before the previous pull

### ISSUE THREAD

**Issue by dzzh** [ingydotnet/git-subrepo#95] opened 2015-10-09 16:00 UTC
This issue seems to be related to #91. The fix I suggested there turned out to be a cure for a symptom, not disease.

`git subrepo branch` command doesn't work correctly when there's a merge of a branch created prior to the previous `git subrepo pull`. This can be reproduced as follows.

Imagine you have host and sub repositories (the latter is a subrepo of the former). Some developers commit directly to sub, some commit to host/sub. Every once in a while a host developer does `git subrepo pull` and `git subrepo push` to sync the changes. Now, consider the following scenario.

1. A host developer creates a feature branch from `master` branch in host to work on some new feature and commits to it.
2. Another developer does `git subrepo pull` in `master`.
3. Some people commit to `master`, their changes may contain subrepo updates.
4. Other people commit directly to sub.
5. The first host developer eventually completes his feature development and merges `feature` to `master`.
6. Another developer triggers `git subrepo pull` again... and we're screwed.

In this flow, when the last `git subrepo pull` is called, subrepo does its regular sequence of `git filter-branch` commands but as a result it gets a non-linear history. The feature branch that was created before the previous `git subrepo pull` execution and merged after the previous `git subrepo pull`, splits. The first it commits gets not only the changes made in this branch, but rather the whole snapshot of the working tree at time. This is not anticipated by the subrepo and it fails terribly when trying to do eventual rebase of `subrepo/sub` onto `refs/subrepo/sub/fetch`.

The best way to avoid this, I believe, is to rewrite the branching algorithm in subrepo. I'll try to come up with a solution.

I have a test script that reproduces the scenario I described earlier, I'll convert it to a test case and commit later today.

**Comment by dzzh** [comment] 2015-10-12 15:49
The referenced code fixed #96 and #95, but after applying it I cannot do push after pull, subrepo reports that there are no new commits to push. This can also be fixed, of course, but I'm not sure I'll find time for this soon.

**Comment by AndrewSmart** [comment] 2015-10-20 23:23
I ran your test for #95, you're right it fails. The last line of the test fails, on the rebase: [`RUN git rebase refs/subrepo/sub/fetch subrepo/sub`](https://github.com/ingydotnet/git-subrepo/blob/679ad12fd684bd72feff90d445c373d9a3d2aa0f/lib/git-subrepo#L442)
The issue here, I'm guessing, is that the the porcelain command `git rebase` fails by design in this situation (e.g. the git devs saw an uncertain situation where they thought a hand-merge would be appropriate to force?). It tried a 3-way merge with an appropriate common-ancestor, and this fails:
```bash
++ git rebase refs/subrepo/sub/fetch subrepo/sub
+ out='First, rewinding head to replay your work on top of it...
Applying: change from host
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging subrepo
CONFLICT (add/add): Merge conflict in subrepo
```
I tried the hand-merge procedure. The mergetool I used auto-merged the conflicting 'subrepo' file correctly:
![screenshot - 10202015 - 04 45 06 pm](https://cloud.githubusercontent.com/assets/5455129/10623310/4669e50c-774b-11e5-8c9b-228bda087671.png)
Not sure why the `git rebase` failed, I really think that 3-way should've succeeded. I have no more time today, but I'll try adding GIT_MERGE_VERBOSITY=5 to that merge to see what is going on.

Sorry, I could be wrong, but that's what my ~40 minutes says :-)

**Comment by AndrewSmart** [comment] 2015-10-21 20:11
Honestly I think the merge behaved appropriately in this situation: ["unambiguous decisions are made automatically, but when there's doubt it's up to the user to decide"](http://stackoverflow.com/a/612747). The hand-merge worked fine for this test.

You could dive deeper into why the merge failed (something about a 'virtual' common ancestor, and a patch not working against it), but that would be in git land, not git-subrepo. I think Ingy's design works great here.

**Comment by dzzh** [comment] 2015-10-22 07:29
Thanks for the observations, it makes sense to try adjusting git merging behavior indeed. It is very conservative for the subrepo merges. However, my impression about this merge was that it's not merely a git problem, but also a subrepo issue related to the way it does rebases. In this situation, it tries to rebase a non-linear branch which adds more unnecessary complexity which confuses git. I think it would be better to preprocess the local changes by squashing them all into a single commit and cherry-picking it later, as I suggest in #96. After this change, we don't have git conflicts.

**Comment by grimmySwe** [comment] 2016-01-22 23:55
Test case for this issue is included in test suite and it works, so I consider this issue closed.

**Closed by grimmySwe** 2016-01-22 23:55 UTC
