### ISSUE TITLE
Address difficulty with common push patterns

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#83] opened 2015-07-21 19:11 UTC
Zmicier emailed me directly:

Hi Ingy,

My name is Zmicier, I’m a software developer and I’m interested in your
git-subrepo extension. I’d like to use it to replace submodules in some of my
projects, so I set up a dummy project to get used to it. There is one thing
about it that I don’t completely understand. Could you please help me to figure
out how it works?

My setup is very simple. I have a parent repo with one txt file and a child
repo with another txt file. The child repo is added to the parent as a subrepo
with git subrepo clone. I can commit changes to the child repo and then do git
subrepo pull in parent to merge them, this works fine. However, when I do a
commit to the parent repo that contains changes to the child repo and do git
subrepo push for backporting them, I always get merge conflicts. All my changes
get squashed into one commit that doesn’t have anything in common with the
history of the child repo, which obviously leads to a conflict. Does it suppose
to work like this or I do something wrong? My impression was that doing a push
should just commit the new changes on top of the child repo history, if there
are no real conflicts. Is it possible to somehow achieve this?

I have attached my dummy repositories to this message in case you will need to
have a look. I expect to do from inside parent and get a merge without
conflicts here.

Cheers, Zmicier

Turning this into an issue to track it within the community. Pushing is the
place we have the most difficulty, so we will start addressing that here.

I'm working on a script to recreate the setup that Zmicier sent me. Stay tuned.

**Comment by ingydotnet** [comment] 2015-07-21 19:20
I think this script reproduces exactly the tarball of 2 repos that was emailed to me: https://gist.github.com/e701b29fde0163ff698b

Here is the output when I run it: https://gist.github.com/e9db129903832e947d53

Zmicier, please confirm that this is correct. I'll show you how to finish this push. Then we can discuss how to make it easier in general.

**Comment by ingydotnet** [comment] 2015-07-21 19:40
OK I made a couple minor mistakes in the setup script. The fixed one is: https://gist.github.com/ef583914e6cef97315d7

The failing `subrepo push` says:

```
The 'git rebase' command failed during your push.
You will need to finish the push by hand. Follow these steps:

  # Resolve the rebase conflicts
  git checkout master
  git subrepo push childrepo subrepo-push/childrepo
```

To finish the `push` successfully I did these steps:

```
git mergetool
git rebase --continue
git checkout master
git subrepo push childrepo subrepo-push/childrepo
```

and it worked fine. Please confirm that this works for you.

I think everything is working as it should, but I'm open to making the experience smoother and also looking into more complicated cases.

I think if you had made a change that was not so close to other recent changes, then git would not have sparked a conflict. Like adding a whole new file or something. I'm not an expert in how git merges things.

**Comment by ingydotnet** [comment] 2015-07-21 19:47
I just confirmed that if you add a new file like `childrepo/child2.txt` to the `parent` repo, then the push works fine (no conflict).

So basically, subrepo was just reporting a real conflict. (I'm fairly certain) This conflict would have happened with merging or rebasing normal branches that were touched in the same way.

**Comment by jawshooah** [comment] 2015-07-21 20:24
I don't understand why there is a conflict at all. No new commits are pushed to `child-upstream` between `git subrepo pull childrepo` and `git subrepo push childrepo`, so the `'Commit from parent for pushing'` commit should be cleanly applied, right?

**Comment by ingydotnet** [comment] 2015-07-21 20:33
Well, maybe you can help me figure it out. Here's the raw deal:

When we push we do this:

* Fetch the upstream (2 commits in child)
* Create a branch of the changes in the subrepo (1 unrelated commit)
* Rebase the 1 commit on top of the 2

I don't know if this makes a difference, but there is no common ancestry between those 2 histories, so this effectively cheery-picking the 1 subrepo commit on top of the 2 upstream commits.

I'll try to recreate this conflict using core git commands (like cherry-pick). (ie no subrepo actions at all).

**Comment by jawshooah** [comment] 2015-07-21 21:00
Ah, right, the problem is that the commits don't share a common ancestor. Perhaps [graft points](https://git.wiki.kernel.org/index.php/GraftPoint) would be helpful here?

**Comment by ingydotnet** [comment] 2015-07-21 21:07
Here is a reproduction script, that you can play with. I does exactly what is happening in the push conflict: https://gist.github.com/2532d2bf6c00f93bb523

Output here: https://gist.github.com/52cb7f06321d0d6c714b

@jawshooah maybe play around with grafts in that script and report back?

Really old versions of subrepo used grafting but that was removed. Now that things are more stable we might be able to play with grafts again.

**Comment by jawshooah** [comment] 2015-07-21 21:09
There is another problem: any commits made before a `git subrepo pull` are ignored by `git subrepo push`:

```bash
$ cd parent
$ echo 'New child file' > childrepo/child2.txt
$ git add childrepo/child2.txt
$ git commit -m 'New child file'

$ git subrepo pull --verbose childrepo
* Fetch the upstream: ../child-upstream (master):
  * Fetch '../child-upstream' (master)
  * Get the upstream subrepo HEAD commit.
  * Create ref 'refs/subrepo/childrepo/fetch'.
* Deleting old 'subrepo/childrepo' branch.
* Create subrepo branch 'subrepo/childrepo':
  * Check if the 'subrepo/childrepo' branch already exists.
  * Make sure there is at least one commit after the last pull.
  * Remove the commits before last pull.
  * Get commits specific to the subdir.
  * Make sure there are *subrepo* commits after the last pull.
  * Remove the previous pull commit.
  * Remove the .gitrepo file from the history.
  * Create branch 'subrepo/childrepo' for this new commit set.
  * Reset to the 'master' branch.
* git rebase  subrepo/childrepo
* Checkout 'master'.
* Commit the new 'childrepo/' content:
  * Check that 'subrepo/childrepo' exists
  * Make sure 'subrepo/childrepo' contains the upstream HEAD.
  * Remove old content of the subdir.
  * Put remote subrepo content into 'childrepo/'.
  * Reset index to original commit.
  * Put info into 'childrepo/.gitrepo' file.
  * Add 'childrepo/' content to the index.
  * Commit to the 'master' branch.
  * Create ref 'refs/subrepo/childrepo/commit'.
* Create ref 'refs/subrepo/childrepo/pull' for branch 'subrepo/childrepo'.
Subrepo 'childrepo' pulled from '../child-upstream' (master).

$ git subrepo push --verbose childrepo
* Fetch the upstream: ../child-upstream (master):
  * Fetch '../child-upstream' (master)
  * Get the upstream subrepo HEAD commit.
  * Create ref 'refs/subrepo/childrepo/fetch'.
* Create subrepo branch 'subrepo-push/childrepo':
  * Check if the 'subrepo-push/childrepo' branch already exists.
  * Make sure there is at least one commit after the last pull.
Subrepo 'childrepo' has no new commits to push.
```

**Comment by ingydotnet** [comment] 2015-07-21 21:19
@jawshooah, I'm out of time to look at this but could you turn this into a new issue, and investigate it further if you are so inclined?

I *think* that subrepo would store the last pull info into the .gitrepo and then filter-branch the subdir from that point.

Remember that `--debug` is also your friend. (And `--DEBUG` is your LOUD friend).

**Comment by dzzh** [comment] 2015-07-21 22:10
Yes, the script is correct. You can even avoid committing to child and pulling from parent, I did it just to prove that pull works as expected.

**Comment by dzzh** [comment] 2015-07-21 22:17
As @jawshooah, I also noticed that there were no common commits between subrepo/childrepo and subrepo-push/childrepo. In this case git treats child.txt as newly created in both branches and cannot figure out which change should be accepted. To resolve this, subrepo-push has to be contain existing subrepo history including the tip of the upstream branch, now you just squash all subrepo history into one commit and try rebasing it onto existing history.

**Comment by dzzh** [comment] 2015-07-21 22:20
I'll dive into the code tomorrow, will try to suggest a solution.

**Comment by ingydotnet** [comment] 2015-07-21 23:52
@dzzh subrepo does not _squash_ history, it uses filter-branch to making a commit history of each commit that affected the subdir, since the last pull. In this case we only had s ingle new commit. So while the subrepo branch only has one commit, it is not a squashed commit.

We want to push the commit messages of every change that affected the subdir. It's up to the committer to realize that a commit message involving a subrepo will likely get pushed to the subrepo too.

A subrepo push can be done by hand like this (for subrepo called `child`):

```
> git subrepo fetch child
> git subrepo branch child
> git subrepo status -v child  # Find all the commits and refs
> git rebase refs/subrepo/child/fetch subrepo/child
> git checkout master
> git push subrepo/child subrepo/child  # remote name and branch name
```

I think that grafts might help out here, but the first thing to do is get all the minimal situations encoded as tests.

**Comment by dzzh** [comment] 2015-07-22 09:00
Ok, squashing may be an incorrect term here. What I meant to say was that this new commit contains not the changes to be merged into the subrepo, but the snapshot of the whole working tree of a subrepo dir. It's like you copy subrepo dir somewhere and do 

   git init
   git add .
   git commit -a -m "commit"

there.

**Comment by ingydotnet** [comment] 2015-07-22 17:07
@dzzh, that's not correct either.

We get all the commits from the (parent) repo that touched the subdir for the (child) subrepo since the last `pull`, then we rebase them on top of the current FETCH_HEAD for the child's upstream.

So say we've made 7 commits to parent since the last `pull` and 3 of them affected the child subdir. The `git subrepo branch ...` pulls out those 3 commits all chained together in a 3 commit long history. Note that the SHA1 refs are different (but that doesn't really matter for our purposes). The commit messages and the tree objects have all the right stuff. The work is actually done by a `git filter-branch --subdirectory ...` command.
 
This is what the `git subrepo branch ...` command does, and `push` calls the same code. The actual code is here: https://github.com/ingydotnet/git-subrepo/tree/master/lib/git-subrepo#L563

This code is where we need to make sure we are doing the right things. The logic may not be perfect and I suspect we can do better regardless.

**Comment by dzzh** [comment] 2015-07-22 17:56
@ingydotnet, I was describing the situation with only one commit to be pushed. If there are more commits, then the first commit will contain a snapshot of child repo's working tree plus the changes from the first commit to be pushed, the other commits will be correctly rebased on top of this. You can easily check it by doing one more commit to child.txt from parent repo, running ```git subrepo branch``` and checking the diffs.

If we want to avoid this situation, we need to include the history of the upstream branch to subrepo-push branch. ```filter-branch``` command is not aware of subrepo existence, thus it starts stacking commits on an empty ground instead of rebasing them onto the head upstream commit. That's basically the problem we have here.

I didn't have much time to look into the code today, will try to do so tomorrow or a bit later, but definitely before the end of this week. It's not about the subrepo implementation details, though, rather about finding a way to do filter-branching on top of existing history, a pure git thing.

**Comment by dzzh** [comment] 2015-07-22 18:04
Here it is. From [filter-branch documentation](https://www.kernel.org/pub/software/scm/git/docs/git-filter-branch.html):

To set a commit (which typically is at the tip of another history) to be the parent of the current initial commit, in order to paste the other history behind the current history

```git filter-branch --parent-filter 'sed "s/^\$/-p <graft-id>/"' HEAD```

**Comment by ingydotnet** [comment] 2015-07-22 18:34
Thanks @dzzh 

I created a branch called `push-patterns`. We should start defining all the permutations of things that can happen surrounding push. Then we codify them as tests.

**Comment by dzzh** [comment] 2015-07-23 10:32
I did some reading on these graft points and it seems they are kind of obsolete, it's recommended to use ```git replace``` instead of them. However, it works differently. If we do ```filter-branch``` with graft-id, all the subsequent history gets rewritten. ```git replace``` doesn't rewrite the history, it only creates a reference to a different commit that shadows the original one. Because of this, pushing back to subrepo upstream doesn't seem to justwork™. ```git replace``` does support ```--graft``` flag that maybe does what we need, but I didn't test it yet.

Rewriting the history with ```graft-id``` does seem to work, though. Also, it's just a commit pointer, not a real graft point, so maybe it's fine to proceed with it. To make push work, I did the following (manually).

```
> git subrepo push childrepo -d #It fails at rebase, as expected. Instead of waiting for the failure, all git commands preceding the rebase can be executed manually.
> git checkout subrepo-push/childrepo
> git filter-branch -f --parent-filter 'sed "s/^\$/-p <UPSTREAM_HEAD_SHA1>/"' HEAD
> git checkout <WORKING_BRANCH> # is it ORIG_HEAD?
> git subrepo push childrepo subrepo-push/childrepo
```

After that I manually updated ```.gitrepo``` by setting "commit" pointer to the tip of children's upstream and by setting "parent" to the tip of my working branch and committed. Everything went well and I was able to do ```git subrepo pull``` after committing directly to subrepo afterwards. This flow can be automated and should work. However, this is a happy flow, will check what's going on if we have a real conflict.

**Comment by jawshooah** [comment] 2015-07-23 16:32
I've forked @ingydotnet's [gist](https://gist.github.com/anonymous/2532d2bf6c00f93bb523) using filter-branch, once [with conflict](https://gist.github.com/jawshooah/69f8fb99ae0e4e51cdee) ([output](https://gist.github.com/jawshooah/b13aef0136054ef8dd9b)) and once [with no conflict](https://gist.github.com/jawshooah/5a91bc22198352e7f12e) ([output](https://gist.github.com/jawshooah/748e750a84750f1765eb)).

Looks like we should be able to do graft the `subrepo-push/childrepo` branch onto `subrepo_commit`, then rebase onto `upstream_head_commit`.

**Comment by jawshooah** [comment] 2015-07-23 17:02
Added the functionality described above in jawshooah/git-subrepo@842d478. Appears to fix the issue demonstrated in https://gist.github.com/ef583914e6cef97315d7.

**Comment by dzzh** [comment] 2015-07-24 07:39
You change does fix the problem with the push, but the references in ```.gitrepo``` don't change and still point to the previous subrepo state. This causes problems when doing ```pull``` next time.

**Comment by dzzh** [comment] 2015-07-24 14:39
I have added the necessary changes to my fork. Not sure if I did everything correctly and considered all the cases, but in my setup it seems to work.

I have two repos A and B, they share a subrepo C. With these changes I'm able to alter subrepo files from A or B and push without a conflict. After that, the repository stays in consistent state, meaning that next pushes and pulls will work fine.

The only thing that has to be taken into account is that push has to be performed with ```-u``` flag, and respectively with specifying a branch (otherwise update doesn't work). So I run push like this: ```git subrepo push childrepo -b master -u```, then it works.

**Comment by mmalcolm** [comment] 2015-08-18 07:09
I think I ran into the same issue today giving subrepo a spin. I then struggled to get it back to the correct state.
I think we will depend on this fix if it works, if we are going to use this.

Hopefully the push can be made to work as well without needing to add the branch and u

Also I hope it will work well for real merge conflicts, that is merge conflicts been different sub tree issues, not implementation based merge conflicts which should all be hidden/avoided etc.
Maybe then a something like 
"git subrepo rebase --continue" or something like that, instead of the raw lines.

I might give the fix a spin

**Comment by grimmySwe** [comment] 2016-01-23 00:07
@dzzh Is this issue still a problem?

**Comment by dzzh** [comment] 2016-01-28 20:43
I can't really tell it as I work with my own fork at the moment. I plan to test your new version one day, but didn't do it yet. Ingy did a test script for this issue available in the second comment, did you try running it?

**Comment by grimmySwe** [comment] 2016-01-29 07:41
I tested to reproduce this with the script in https://github.com/ingydotnet/git-subrepo/issues/83#issuecomment-123457036 but on the latest master it works without conflicts.

So closing this issue for now.

**Closed by grimmySwe** 2016-01-29 07:41 UTC
