### ISSUE TITLE
Cannot lock ref with '.' in path

### ISSUE THREAD

**Issue by kentfredric** [ingydotnet/git-subrepo#13] opened 2014-03-04 11:25 UTC
In conjunction with bug #11, it seems somewhere in the logic is trying to create paths in `refs/` with `.` in the path, which is invalid, and will never work.

```coffeescript
git subrepo pull --all -v
>>> git rev-parse --short HEAD
>>> git rev-parse --abbrev-ref HEAD
>>> git rev-parse HEAD
>>> git rev-parse --is-inside-work-tree
>>> git rev-parse --verify HEAD
>>> git config --file=./.build/4aigJj5LnU/maint-travis-ci/.gitrepo subrepo.remote
>>> git config --file=./.build/4aigJj5LnU/maint-travis-ci/.gitrepo subrepo.branch
>>> git config --file=./.build/4aigJj5LnU/maint-travis-ci/.gitrepo subrepo.commit
>>> git config --file=./.build/4aigJj5LnU/maint-travis-ci/.gitrepo subrepo.parent
>>> git fetch --quiet https://github.com/kentfredric/travis-scripts.git master
>>> git rev-parse FETCH_HEAD
>>> git remote add subrepo/./.build/4aigJj5LnU/maint-travis-ci https://github.com/kentfredric/travis-scripts.git
fatal: 'subrepo/./.build/4aigJj5LnU/maint-travis-ci' is not a valid remote name
>>> git for-each-ref refs/subrepo/remote/./.build/4aigJj5LnU/maint-travis-ci
>>> git update-ref refs/subrepo/remote/./.build/4aigJj5LnU/maint-travis-ci 7c80dffae0d7e39b20582e368d85c290429219fa
fatal: Cannot lock the ref 'refs/subrepo/remote/./.build/4aigJj5LnU/maint-travis-ci'.
subrepo './.build/4aigJj5LnU/maint-travis-ci' is up to date
>>> git config --file=./.build/ZHF9Z1Gfsu/maint-travis-ci/.gitrepo subrepo.remote
>>> git config --file=./.build/ZHF9Z1Gfsu/maint-travis-ci/.gitrepo subrepo.branch
>>> git config --file=./.build/ZHF9Z1Gfsu/maint-travis-ci/.gitrepo subrepo.commit
>>> git config --file=./.build/ZHF9Z1Gfsu/maint-travis-ci/.gitrepo subrepo.parent
>>> git fetch --quiet https://github.com/kentfredric/travis-scripts.git master
>>> git rev-parse FETCH_HEAD
>>> git remote add subrepo/./.build/ZHF9Z1Gfsu/maint-travis-ci https://github.com/kentfredric/travis-scripts.git
fatal: 'subrepo/./.build/ZHF9Z1Gfsu/maint-travis-ci' is not a valid remote name
>>> git for-each-ref refs/subrepo/remote/./.build/ZHF9Z1Gfsu/maint-travis-ci
>>> git update-ref refs/subrepo/remote/./.build/ZHF9Z1Gfsu/maint-travis-ci 7c80dffae0d7e39b20582e368d85c290429219fa
fatal: Cannot lock the ref 'refs/subrepo/remote/./.build/ZHF9Z1Gfsu/maint-travis-ci'.
subrepo './.build/ZHF9Z1Gfsu/maint-travis-ci' is up to date
>>> git config --file=./Path-FindDev-0.4.3/maint-travis-ci/.gitrepo subrepo.remote
>>> git config --file=./Path-FindDev-0.4.3/maint-travis-ci/.gitrepo subrepo.branch
>>> git config --file=./Path-FindDev-0.4.3/maint-travis-ci/.gitrepo subrepo.commit
>>> git config --file=./Path-FindDev-0.4.3/maint-travis-ci/.gitrepo subrepo.parent
>>> git fetch --quiet https://github.com/kentfredric/travis-scripts.git master
>>> git rev-parse FETCH_HEAD
>>> git remote add subrepo/./Path-FindDev-0.4.3/maint-travis-ci https://github.com/kentfredric/travis-scripts.git
fatal: 'subrepo/./Path-FindDev-0.4.3/maint-travis-ci' is not a valid remote name
>>> git for-each-ref refs/subrepo/remote/./Path-FindDev-0.4.3/maint-travis-ci
>>> git update-ref refs/subrepo/remote/./Path-FindDev-0.4.3/maint-travis-ci 7c80dffae0d7e39b20582e368d85c290429219fa
fatal: Cannot lock the ref 'refs/subrepo/remote/./Path-FindDev-0.4.3/maint-travis-ci'.
subrepo './Path-FindDev-0.4.3/maint-travis-ci' is up to date
>>> git config --file=./Path-FindDev-0.5.0/maint-travis-ci/.gitrepo subrepo.remote
>>> git config --file=./Path-FindDev-0.5.0/maint-travis-ci/.gitrepo subrepo.branch
>>> git config --file=./Path-FindDev-0.5.0/maint-travis-ci/.gitrepo subrepo.commit
>>> git config --file=./Path-FindDev-0.5.0/maint-travis-ci/.gitrepo subrepo.parent
>>> git fetch --quiet https://github.com/kentfredric/travis-scripts.git master
>>> git rev-parse FETCH_HEAD
>>> git remote add subrepo/./Path-FindDev-0.5.0/maint-travis-ci https://github.com/kentfredric/travis-scripts.git
fatal: 'subrepo/./Path-FindDev-0.5.0/maint-travis-ci' is not a valid remote name
>>> git for-each-ref refs/subrepo/remote/./Path-FindDev-0.5.0/maint-travis-ci
>>> git update-ref refs/subrepo/remote/./Path-FindDev-0.5.0/maint-travis-ci 7c80dffae0d7e39b20582e368d85c290429219fa
fatal: Cannot lock the ref 'refs/subrepo/remote/./Path-FindDev-0.5.0/maint-travis-ci'.
subrepo './Path-FindDev-0.5.0/maint-travis-ci' is up to date
>>> git config --file=./maint-travis-ci/.gitrepo subrepo.remote
>>> git config --file=./maint-travis-ci/.gitrepo subrepo.branch
>>> git config --file=./maint-travis-ci/.gitrepo subrepo.commit
>>> git config --file=./maint-travis-ci/.gitrepo subrepo.parent
>>> git fetch --quiet https://github.com/kentfredric/travis-scripts.git master
>>> git rev-parse FETCH_HEAD
>>> git remote add subrepo/./maint-travis-ci https://github.com/kentfredric/travis-scripts.git
fatal: 'subrepo/./maint-travis-ci' is not a valid remote name
>>> git for-each-ref refs/subrepo/remote/./maint-travis-ci
>>> git update-ref refs/subrepo/remote/./maint-travis-ci 7c80dffae0d7e39b20582e368d85c290429219fa
fatal: Cannot lock the ref 'refs/subrepo/remote/./maint-travis-ci'.
subrepo './maint-travis-ci' is up to date
```

**Comment by ingydotnet** [comment] 2016-01-22 20:12
Closing. Can't reproduce.

**Closed by ingydotnet** 2016-01-22 20:12 UTC
