### ISSUE TITLE
Endless conflicts

### ISSUE THREAD

**Issue by feliperaul** [ingydotnet/git-subrepo#444] opened 2020-03-15 12:05 UTC
I really gave this neat project a go, but my user experience on the last month has been very difficult due to the sheer amount of conflicts every time I use `git subrepo pull` with the `rebase` strategy.

I find myself having to solve conflicts on every single commit that has happened on the imported subrepo, and no matter how many times I resolve them, they always comeback on every single pull.

Also, I'm seeing a lot of conflicts that are not conflicts at all, like, for instance, this:

![image](https://user-images.githubusercontent.com/743879/76701024-0d29dc80-669c-11ea-9396-560a09996c3d.png)

There''s no difference at all between those two lines, and yet I have to fix this every single time.

With 10+ commits on the imported repo, every single `git subrepo pull` is taking around 15 minutes to solve already, and they are all "fake" conflicts like this.

**Comment by admorgan** [comment] 2020-03-15 14:29
Duplicate of #445

**Closed by admorgan** 2020-03-15 14:29 UTC
Labels: Duplicate
