### ISSUE TITLE
git subrepo init fails

### ISSUE THREAD

**Issue by kilowu** [ingydotnet/git-subrepo#192] opened 2016-05-31 10:06 UTC
Repo has a sub-directory named java.
$ git subrepo init java
git-subrepo/lib/git-subrepo: line 1174: printf: `+subdir': not a valid identifier

**Comment by grimmySwe** [comment] 2016-06-27 11:08
Could you please add some more information for this case:
What subrepo version are you using? 
Can you reproduce this error? How? Can you create a simple example to reproduce it?

**Comment by kilowu** [comment] 2016-08-22 16:40
I'm using the latest version of subrepo (pulled from master).

I found out that the problem is about to the bash environment. 

There is a [[ command's =~ operator in git-subrepo line 1166:
```bash
   if [[ $arg =~ ^\+ ]]; then
      if [[ $i -ge $num ]]; then
        usage-error "Command '$command' requires arg '${arg#+}'."
      fi
      printf -v ${arg#+} "${command_arguments[i]}"
    # Look for function name after ':' to provide a default value
    else
      if [[ $i -lt $num ]]; then
        printf -v ${arg%:*} "${command_arguments[i]}"
      elif [[ $arg =~ : ]]; then
        "${arg#*:}"
      fi
    fi
```

The rhs argument is ``^\+``. It does not match the "+pattern" in my machine. I tried to change it to ``^\\+`` and after that it worked in my environment.

It looks like a bash compatibility issue.

**Comment by hainm** [comment] 2016-09-26 18:11
> The rhs argument is ^\+. It does not match the "+pattern" in my machine. I tried to change it to ^\\+ and after that it worked in my environment.

I got the same issue with current master branch (1e795953d4265abacf828ed7e66036cff281fc7c) and your solution works for me too.

**Comment by ingydotnet** [comment] 2016-09-26 18:33
@kilowu @hainm could you both post the output of:

```
uname -a && echo && bash --version
```

**Comment by hainm** [comment] 2016-09-26 18:34
mine
```bash
Linux [...] Wed Sep 3 16:22:34 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.
```

**Comment by ingydotnet** [comment] 2016-09-26 18:42
@hainm which linux distro and distro version?

**Comment by hainm** [comment] 2016-09-26 18:45
```bash
$ cat /proc/version 
Linux version 2.6.18-371.12.1.el5 (mockbuild@builder17.centos.org) 
(gcc version 4.1.2 20080704 (Red Hat 
4.1.2-54)) #1 SMP Wed Sep 3 16:22:34 EDT 2014
```

**Comment by ingydotnet** [comment] 2016-09-26 18:51
Ok so I think we are dealing with the oldest possible supported Bashes. I refuse to support Bash before it added regex. But there are some bash versions with buggy regex that I will support. Here is the reproduction and the workaround:

```
> uname -a
Darwin bigshoes.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
> bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
> [[ "+foo" =~ ^+ ]] && echo OK
> [[ "+foo" =~ ^\+ ]] && echo OK
OK
> [[ "+foo" =~ ^\\+ ]] && echo OK
> shopt -s compat31
> [[ "+foo" =~ ^+ ]] && echo OK
> [[ "+foo" =~ ^\+ ]] && echo OK
> [[ "+foo" =~ ^\\+ ]] && echo OK
OK
>
```

I'll make a fix, and ask @hainm to test it. Give me a moment.

**Comment by ingydotnet** [comment] 2016-09-26 19:02
@hainm would you please test the fix on branch `issue/192`.

BTW, you should be able to run `make test` on both `master` and `issue/192` branches to see the fail and the fix. (Well hopefully there is coverage).

If it works out, let me know and I'll merge to master... after lunch!

**Comment by hainm** [comment] 2016-09-26 19:10
I got different failures with `issue/192`

```bash
git-subrepo/lib/git-subrepo: line 1166: shopt: compat31: invalid shell option name
```

master
```bash
git-subrepo/lib/git-subrepo: line 1174: printf: `+subrepo_remote': not a valid identifie
```

**Comment by ingydotnet** [comment] 2016-09-26 21:26
Oh dang. That makes sense. I fixed the fix and force pushed to `issue/192`. @hainm Can you test that?

Also report back if any other failing tests in the `make test` suite. Cheers!

**Comment by hainm** [comment] 2016-09-26 21:33
tests passed. thanks.

**Comment by ingydotnet** [comment] 2016-09-26 21:43
Fixed and closing.

Thanks @hainm for testing this.

**Closed by ingydotnet** 2016-09-26 21:43 UTC
Labels: bug
