### ISSUE TITLE
GitHub no longer renders the Readme

### ISSUE THREAD

**Issue by alcrene** [ingydotnet/git-subrepo#593] opened 2023-08-08 11:19 UTC
This seems to be a change on the GitHub side, but the unfortunate result for your project is that the most obvious documentation is no longer user-friendly :-(. (There’s still the [wiki](https://github.com/ingydotnet/git-subrepo/wiki), but I would wager that most people will not think to look there without being pointed to it.)

A quick temporary fix could be to add a link to the wiki under the "Documentation" heading in the right sidebar.

**Comment by admorgan** [comment] 2023-08-09 18:14
Thanks for the heads up. I will try to figure out what changed tonight.

**Comment by JWCS** [comment] 2023-08-12 23:12
Seems to be a github regression that others have noticed; I hear there's an issue somewhere to fix it.
In the meantime, I used the online pod renderer, perhaps this could help others:
https://metacpan.org/pod2html

**Comment by admorgan** [comment] 2023-09-19 21:37
Fixed by Github https://github.com/github/markup/issues/1715

**Closed by admorgan** 2023-09-19 21:37 UTC
Labels: Bug
